# Generated by Django 5.2.7 on 2025-10-08 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('service', models.CharField(choices=[('SOFTWARE DEVELOPMENT SERVICE', 'SOFTWARE DEVELOPMENT SERVICE'), ('PROFESSIONAL COMPUTER AND IT EDUCATION', 'PROFESSIONAL COMPUTER AND IT EDUCATION'), ('DIGITAL ADVERTISING AND BUSINESS BRANDING', 'DIGITAL ADVERTISING AND BUSINESS BRANDING'), ('INTERNATIONAL UNIVERSITY ADMISSION PROCESSING', 'INTERNATIONAL UNIVERSITY ADMISSION PROCESSING'), ('Others', 'Others')], max_length=100, verbose_name='Service Type')),
                ('message', models.TextField(verbose_name='Project Details/Message')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'Quote Submission',
                'verbose_name_plural': 'Quote Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('service', models.CharField(choices=[('SOFTWARE DEVELOPMENT SERVICE', 'SOFTWARE DEVELOPMENT SERVICE'), ('PROFESSIONAL COMPUTER AND IT EDUCATION', 'PROFESSIONAL COMPUTER AND IT EDUCATION'), ('DIGITAL ADVERTISING AND BUSINESS BRANDING', 'DIGITAL ADVERTISING AND BUSINESS BRANDING'), ('INTERNATIONAL UNIVERSITY ADMISSION PROCESSING', 'INTERNATIONAL UNIVERSITY ADMISSION PROCESSING'), ('WEBSITE SEO Optimization', 'WEBSITE SEO Optimization'), ('Others', 'Others')], max_length=100, verbose_name='Service Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
