# Generated by Django 5.2.7 on 2025-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
